### ISSUE TITLE
App does not update on android

### ISSUE THREAD

**Issue by tvouga** [indie-pocket/indie-pocket#13] opened 2020-04-10 10:36 UTC

**Comment by tvouga** [comment] 2020-04-10 10:47
Still on 5.1 on android. Version 5.2 from applivery does not install upon manual download; version 5.3 not available yet (staging? where is it available?)

**Comment by ineiti** [comment] 2020-04-11 10:30
Uploaded 0.5.3 (I insist on the `0.` ;)

With regard to staging, can you give some more information? Did you install staging? Do you want to install it? Does the version say `0.5.1-s`?

**Comment by ineiti** [comment] 2020-04-11 10:31
If the problem is resolved, please give a short description how you resolved it, and close the comment.

**Comment by ineiti** [comment] 2020-04-15 14:33
time out - closing. Please re-open if it's still a problem.

**Closed by ineiti** 2020-04-15 14:33 UTC
Labels: mobile
